spring:
  application:
    name: student-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/studentdb
    username: postgres
    password: Adesanya+123.
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
  
server:
  port: 8113

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  tracing:
    sampling:
      probability: 1.0   

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans